# Generated by Django 4.1.5 on 2023-02-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(max_length=10)),
                ('phone_no', models.IntegerField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('bill_no', models.CharField(max_length=10)),
                ('exit_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='food_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.CharField(max_length=10)),
                ('food_name', models.CharField(max_length=20)),
                ('catagory', models.CharField(max_length=20)),
                ('price', models.IntegerField(max_length=4)),
                ('avg_review', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=10)),
                ('tb_no', models.CharField(max_length=10)),
                ('amount', models.IntegerField(max_length=5)),
                ('payment', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order_food_mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=10)),
                ('food_id', models.CharField(max_length=10)),
                ('quantity', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tb_no', models.CharField(max_length=10)),
                ('Qr_no', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
