# Generated by Django 4.1.5 on 2023-02-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food_item',
            name='avg_review',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food_item',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order_food_mapping',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
