# Generated by Django 4.1.7 on 2023-02-28 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_customer_id_remove_food_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bill_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tb_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.table'),
        ),
        migrations.AlterField(
            model_name='order_food_mapping',
            name='food_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.food_item'),
        ),
        migrations.AlterField(
            model_name='order_food_mapping',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.order'),
        ),
    ]
