# Generated by Django 4.1.7 on 2023-03-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_customer_bill_no_alter_order_tb_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='tb_no',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
