# Generated by Django 4.1.7 on 2023-03-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_table_tb_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='tb_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
