# Generated by Django 4.1.7 on 2023-03-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_order_order_id_alter_table_tb_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='tb_no',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
