# Generated by Django 4.1.5 on 2023-03-06 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_rename_order_food_mapping_ofmapping'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OFmapping',
            new_name='Order_food_mapping',
        ),
    ]
