# Generated by Django 4.1.7 on 2023-03-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_rename_ofmapping_order_food_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='c_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='exit_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
