# Generated by Django 4.1.7 on 2023-03-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_order_food_mapping_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_food_mapping',
            name='modification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
