# Generated by Django 4.1.7 on 2023-03-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_order_food_mapping_modification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.BooleanField(default='Remaining'),
        ),
    ]
