# Generated by Django 4.1.7 on 2023-03-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_alter_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(default='Remaining', max_length=10),
        ),
    ]
