# Generated by Django 4.1.5 on 2023-03-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_alter_order_amount_alter_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=models.FloatField(max_length=11),
        ),
    ]
